/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.analysis;

import dot.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseACreateGraph(ACreateGraph node);
    void caseACreateNode(ACreateNode node);
    void caseACreatePcNodes(ACreatePcNodes node);

    void caseTEquals(TEquals node);
    void caseTSemicolon(TSemicolon node);
    void caseTComma(TComma node);
    void caseTLCb(TLCb node);
    void caseTRCb(TRCb node);
    void caseTLBr(TLBr node);
    void caseTRBr(TRBr node);
    void caseTDirectedEdge(TDirectedEdge node);
    void caseTUndirectedEdge(TUndirectedEdge node);
    void caseTStrict(TStrict node);
    void caseTDigraph(TDigraph node);
    void caseTGraph(TGraph node);
    void caseTSubgraph(TSubgraph node);
    void caseTComment(TComment node);
    void caseTEol(TEol node);
    void caseTBlank(TBlank node);
    void caseTId(TId node);
    void caseTType(TType node);
    void caseEOF(EOF node);
}
