/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.analysis;

import java.util.*;
import dot.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPCreateGraph().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inACreateGraph(ACreateGraph node)
    {
        defaultIn(node);
    }

    public void outACreateGraph(ACreateGraph node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreateGraph(ACreateGraph node)
    {
        inACreateGraph(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outACreateGraph(node);
    }

    public void inACreateNode(ACreateNode node)
    {
        defaultIn(node);
    }

    public void outACreateNode(ACreateNode node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreateNode(ACreateNode node)
    {
        inACreateNode(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outACreateNode(node);
    }

    public void inACreatePcNodes(ACreatePcNodes node)
    {
        defaultIn(node);
    }

    public void outACreatePcNodes(ACreatePcNodes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreatePcNodes(ACreatePcNodes node)
    {
        inACreatePcNodes(node);
        if(node.getParent() != null)
        {
            node.getParent().apply(this);
        }
        if(node.getChild() != null)
        {
            node.getChild().apply(this);
        }
        outACreatePcNodes(node);
    }
}
