/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.lexer;

import java.io.*;
import dot.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquals(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLCb(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRCb(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBr(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBr(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDirectedEdge(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUndirectedEdge(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStrict(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDigraph(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGraph(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubgraph(line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TType(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {44, 44, 6}, {45, 45, 7}, {46, 46, 8}, {47, 47, 9}, {48, 57, 10}, {59, 59, 11}, {61, 61, 12}, {65, 90, 13}, {91, 91, 14}, {92, 92, 15}, {93, 93, 16}, {95, 95, 17}, {97, 99, 18}, {100, 100, 19}, {101, 101, 20}, {102, 102, 18}, {103, 103, 21}, {104, 109, 18}, {110, 110, 22}, {111, 114, 18}, {115, 115, 23}, {116, 122, 18}, {123, 123, 24}, {125, 125, 25}, },
            {{9, 9, 1}, {10, 10, 26}, {13, 13, 27}, {32, 32, 4}, },
            {{9, 32, -3}, },
            {{9, 9, 1}, {10, 10, 28}, {13, 32, -3}, },
            {{9, 32, -3}, },
            {{32, 32, 29}, {34, 34, 30}, {46, 46, 31}, {48, 57, 32}, {65, 90, 33}, {92, 92, 34}, {95, 95, 35}, {97, 122, 36}, },
            {},
            {{45, 45, 37}, {62, 62, 38}, },
            {{48, 57, 39}, },
            {{42, 42, 40}, {47, 47, 41}, },
            {{46, 46, 42}, {48, 57, 10}, {65, 90, 13}, {92, 92, 15}, {95, 95, 17}, {97, 122, 18}, },
            {},
            {},
            {{46, 46, 8}, {48, 122, -12}, },
            {},
            {{46, 122, -15}, },
            {},
            {{46, 122, -15}, },
            {{46, 122, -15}, },
            {{46, 95, -15}, {97, 104, 18}, {105, 105, 43}, {106, 122, 18}, },
            {{46, 95, -15}, {97, 99, 18}, {100, 100, 44}, {101, 122, 18}, },
            {{46, 95, -15}, {97, 113, 18}, {114, 114, 45}, {115, 122, 18}, },
            {{46, 95, -15}, {97, 110, 18}, {111, 111, 46}, {112, 122, 18}, },
            {{46, 95, -15}, {97, 115, 18}, {116, 116, 47}, {117, 117, 48}, {118, 122, 18}, },
            {},
            {},
            {{9, 32, -3}, },
            {{9, 9, 1}, {10, 10, 49}, {13, 32, -3}, },
            {{9, 32, -3}, },
            {{32, 122, -7}, },
            {},
            {{48, 57, 50}, },
            {{32, 34, -7}, {46, 46, 51}, {48, 122, -7}, },
            {{32, 122, -7}, },
            {{32, 122, -7}, },
            {{32, 122, -7}, },
            {{32, 122, -7}, },
            {},
            {},
            {{46, 46, 8}, {48, 57, 52}, {65, 122, -12}, },
            {{0, 41, 53}, {42, 42, 54}, {43, 65535, 53}, },
            {{0, 9, 55}, {10, 10, 56}, {11, 12, 55}, {13, 13, 57}, {14, 65535, 55}, },
            {{46, 122, -41}, },
            {{46, 95, -15}, {97, 102, 18}, {103, 103, 58}, {104, 122, 18}, },
            {{46, 102, -45}, {103, 103, 59}, {104, 122, 18}, },
            {{46, 95, -15}, {97, 97, 60}, {98, 122, 18}, },
            {{46, 99, -22}, {100, 100, 61}, {101, 122, 18}, },
            {{46, 113, -23}, {114, 114, 62}, {115, 122, 18}, },
            {{46, 95, -15}, {97, 97, 18}, {98, 98, 63}, {99, 122, 18}, },
            {{9, 32, -3}, },
            {{32, 46, -7}, {48, 57, 64}, {65, 122, -7}, },
            {{32, 122, -52}, },
            {{46, 46, 42}, {48, 122, -41}, },
            {{0, 65535, -42}, },
            {{0, 41, 65}, {42, 42, 54}, {43, 46, 65}, {47, 47, 66}, {48, 65535, 65}, },
            {{0, 65535, -43}, },
            {},
            {{10, 10, 67}, },
            {{46, 113, -23}, {114, 114, 68}, {115, 122, 18}, },
            {{46, 95, -15}, {97, 100, 18}, {101, 101, 69}, {102, 122, 18}, },
            {{46, 95, -15}, {97, 111, 18}, {112, 112, 70}, {113, 122, 18}, },
            {{46, 100, -61}, {101, 101, 71}, {102, 122, 18}, },
            {{46, 104, -21}, {105, 105, 72}, {106, 122, 18}, },
            {{46, 102, -45}, {103, 103, 73}, {104, 122, 18}, },
            {{32, 46, -34}, {48, 122, -52}, },
            {{0, 41, 74}, {42, 42, 75}, {43, 65535, 74}, },
            {},
            {},
            {{46, 95, -15}, {97, 97, 76}, {98, 122, 18}, },
            {{46, 122, -15}, },
            {{46, 95, -15}, {97, 103, 18}, {104, 104, 77}, {105, 122, 18}, },
            {{46, 122, -15}, },
            {{46, 95, -15}, {97, 98, 18}, {99, 99, 78}, {100, 122, 18}, },
            {{46, 113, -23}, {114, 114, 79}, {115, 122, 18}, },
            {{0, 65535, -67}, },
            {{0, 41, 65}, {42, 42, 75}, {43, 65535, -56}, },
            {{46, 111, -62}, {112, 112, 80}, {113, 122, 18}, },
            {{46, 122, -15}, },
            {{46, 115, -25}, {116, 116, 81}, {117, 122, 18}, },
            {{46, 95, -15}, {97, 97, 82}, {98, 122, 18}, },
            {{46, 103, -72}, {104, 104, 83}, {105, 122, 18}, },
            {{46, 122, -15}, },
            {{46, 111, -62}, {112, 112, 84}, {113, 122, 18}, },
            {{46, 122, -15}, },
            {{46, 103, -72}, {104, 104, 85}, {105, 122, 18}, },
            {{46, 122, -15}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {16, 15, 14, 14, 15, -1, 2, -1, -1, -1, 16, 1, 0, 16, 5, 16, 6, 16, 16, 16, 16, 16, 16, 16, 3, 4, 15, 15, 14, -1, 16, -1, -1, -1, -1, -1, -1, 8, 7, 16, -1, -1, 16, 16, 16, 16, 16, 16, 16, 15, -1, -1, 16, -1, -1, -1, 13, 13, 16, 16, 16, 16, 16, 16, -1, -1, 13, 13, 16, 16, 16, 16, 16, 16, -1, -1, 16, 11, 16, 16, 16, 9, 16, 10, 16, 12, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
