/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.parser;

import dot.node.*;
import dot.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTEquals(@SuppressWarnings("unused") TEquals node)
    {
        this.index = 0;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLCb(@SuppressWarnings("unused") TLCb node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRCb(@SuppressWarnings("unused") TRCb node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLBr(@SuppressWarnings("unused") TLBr node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRBr(@SuppressWarnings("unused") TRBr node)
    {
        this.index = 5;
    }

    @Override
    public void caseTDirectedEdge(@SuppressWarnings("unused") TDirectedEdge node)
    {
        this.index = 6;
    }

    @Override
    public void caseTUndirectedEdge(@SuppressWarnings("unused") TUndirectedEdge node)
    {
        this.index = 7;
    }

    @Override
    public void caseTStrict(@SuppressWarnings("unused") TStrict node)
    {
        this.index = 8;
    }

    @Override
    public void caseTDigraph(@SuppressWarnings("unused") TDigraph node)
    {
        this.index = 9;
    }

    @Override
    public void caseTGraph(@SuppressWarnings("unused") TGraph node)
    {
        this.index = 10;
    }

    @Override
    public void caseTSubgraph(@SuppressWarnings("unused") TSubgraph node)
    {
        this.index = 11;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 12;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 13;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 14;
    }
}
