/* This file was generated by SableCC (http://www.sablecc.org/). */

package dot.node;

import dot.analysis.*;

@SuppressWarnings("nls")
public final class TStrict extends Token
{
    public TStrict()
    {
        super.setText("strict");
    }

    public TStrict(int line, int pos)
    {
        super.setText("strict");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStrict(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStrict(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStrict text.");
    }
}
